(()=>{
const $=s=>document.querySelector(s);
function runs(){try{return JSON.parse(localStorage.getItem('ep_backtest_runs')||'[]')}catch{return[]}}
function normalizeTf(tf){return String(tf||'').toUpperCase().replace('1H','H1').replace('15M','M15').replace('5M','M5').replace('1D','D1')}
function latest(market,sym,tf){const target=normalizeTf(tf);return runs().filter(x=>x&&x.version==='robust-v3'&&x.market===market&&x.sym===sym&&(!target||normalizeTf(x.tf)===target)).sort((a,b)=>(b.ts||0)-(a.ts||0))[0]||null}
function context(market,sym,tf){const r=latest(market,sym,tf);if(!r)return{status:'NO_DATA',label:'Backtest: sem dados',detail:'Ainda não existe Backtest V3 salvo para este ativo/timeframe.',informational:true};const o=r.oos||{},n=+o.n||0,pf=+o.pf||0,exp=+o.exp||0;let status='NEUTRAL',label='Backtest: neutro';if(n<30){status='LOW_SAMPLE';label='Backtest: amostra insuficiente'}else if(pf>=1.2&&exp>0){status='FAVORABLE';label='Backtest: favorável'}else if(pf<1||exp<0){status='UNFAVORABLE';label='Backtest: desfavorável'}return{status,label,detail:`OOS ${n} ops • PF ${pf.toFixed(2)} • Exp ${exp.toFixed(3)}R`,run:r,informational:true}}
function render(){let host=$('#backtestLiveContext');if(!host)return;let market=$('#btMarket')?.value||'crypto',sym=$('#btAsset')?.value,tf=$('#btTf')?.value;if(!sym){host.innerHTML='<span class="sub">Backtest é apenas informativo e nunca bloqueia sinais do Motor.</span>';return}let c=context(market,sym,tf);host.innerHTML=`<div class="wf-verdict pending"><b>${c.label}</b><span>${c.detail}</span></div><p class="sub"><b>Somente informação:</b> este resultado histórico não entra no cálculo do score, não altera COMPRA/VENDA e não bloqueia sinais do Motor.</p>`}
function inject(){let area=$('#backtestArea');if(!area||$('#backtestLiveContext'))return;let d=document.createElement('div');d.id='backtestLiveContext';d.className='wf-block';let status=$('#btStatus');status?.before(d);['btMarket','btAsset','btTf'].forEach(id=>$('#'+id)?.addEventListener('change',()=>setTimeout(render,0)));window.addEventListener('ep-statistics-updated',render);render()}
window.EPBacktestContext={get:context,latest};setTimeout(inject,700);
})();