(()=>{
const $=s=>document.querySelector(s),fmt=(n,d=2)=>Number.isFinite(+n)?(+n).toLocaleString('pt-BR',{maximumFractionDigits:d}):'—',avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const CRYPTO=[['BTCUSDT','BTC'],['ETHUSDT','ETH'],['SOLUSDT','SOL'],['BNBUSDT','BNB'],['XRPUSDT','XRP'],['ADAUSDT','ADA'],['DOGEUSDT','DOGE'],['AVAXUSDT','AVAX'],['LINKUSDT','LINK'],['DOTUSDT','DOT'],['LTCUSDT','LTC'],['BCHUSDT','BCH'],['TRXUSDT','TRX'],['UNIUSDT','UNI'],['AAVEUSDT','AAVE'],['SUIUSDT','SUI'],['NEARUSDT','NEAR'],['APTUSDT','APT'],['ARBUSDT','ARB'],['OPUSDT','OP']];
const B3=[['PETR4','Petrobras'],['VALE3','Vale'],['ITUB4','Itaú Unibanco'],['BBAS3','Banco do Brasil'],['BBDC4','Bradesco'],['B3SA3','B3'],['PRIO3','PRIO'],['WEGE3','WEG'],['EMBR3','Embraer'],['RENT3','Localiza'],['SUZB3','Suzano'],['ELET3','Eletrobras'],['EQTL3','Equatorial'],['RADL3','RD Saúde'],['GGBR4','Gerdau'],['CSNA3','CSN'],['MGLU3','Magazine Luiza'],['HAPV3','Hapvida'],['BHIA3','Grupo Casas Bahia'],['ABEV3','Ambev']];
const TFS={M5:'5m',M15:'15m',H1:'1h',D1:'1d'},B3CFG={M5:{range:'5d',interval:'5m'},M15:{range:'5d',interval:'15m'},H1:{range:'1mo',interval:'1h'},D1:{range:'1y',interval:'1d'}};
function ema(v,p){if(!v.length)return[];let k=2/(p+1),o=[v[0]];for(let i=1;i<v.length;i++)o.push(v[i]*k+o[i-1]*(1-k));return o}
function rsi(c,p=7){if(c.length<=p)return NaN;let g=0,l=0;for(let i=1;i<=p;i++){let d=c[i].c-c[i-1].c;d>=0?g+=d:l-=d}let ag=g/p,al=l/p;for(let i=p+1;i<c.length;i++){let d=c[i].c-c[i-1].c;ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al?100-100/(1+ag/al):100}
function cci(c,p=14){if(c.length<p)return NaN;let a=c.slice(-p).map(x=>(x.h+x.l+x.c)/3),m=avg(a),d=avg(a.map(x=>Math.abs(x-m)));return d?(a.at(-1)-m)/(0.015*d):0}
function atr(c,p=14){if(c.length<p+1)return NaN;let a=[];for(let i=1;i<c.length;i++)a.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return avg(a.slice(-p))}
function vwap(c){let pv=0,v=0;c.forEach(x=>{let tp=(x.h+x.l+x.c)/3;pv+=tp*x.v;v+=x.v});return pv/(v||1)}
function signal(c){let close=c.map(x=>x.c),last=c.at(-1),prev=c.at(-2),rv=rsi(c),cv=cci(c),e20=ema(close,20),e30=ema(close,30),line=close.map((_,i)=>e20[i]-e30[i]),sig=ema(line,60),mh=line.at(-1)-sig.at(-1),vw=vwap(c.slice(-80)),v20=avg(c.slice(-21,-1).map(x=>x.v)),vr=last.v/(v20||last.v),at=atr(c),bull=0,bear=0,add=(w,d)=>d>0?bull+=w:d<0?bear+=w:0;
add(15,last.c-vw);add(15,mh);if(rv>=55&&rv<80)add(8,1);else if(rv<=45&&rv>20)add(8,-1);if(cv>0&&cv<200)add(5,1);else if(cv<0&&cv>-200)add(5,-1);if(vr>=1.5)add(15,last.c-prev.c);else if(vr>=1.2)add(10,last.c-prev.c);let w=c.slice(-21),ph=Math.max(...w.slice(0,-1).map(x=>x.h)),pl=Math.min(...w.slice(0,-1).map(x=>x.l));if(last.c>ph)add(20,1);else if(last.c<pl)add(20,-1);else add(8,last.c-(ph+pl)/2);if(Number.isFinite(at)&&at>0){let impulse=(last.c-prev.c)/at;if(Math.abs(impulse)>=.5)add(10,impulse);else if(Math.abs(impulse)>=.2)add(5,impulse)}if(rv<=20&&cv<=-100)add(12,1);if(rv>=80&&cv>=100)add(12,-1);bull=Math.min(100,Math.round(bull));bear=Math.min(100,Math.round(bear));let dir=bull>=bear?'BUY':'SELL',score=Math.max(bull,bear);return{dir,score,atr:at,rsi:rv,cci:cv,vr,macd:mh,vwap:vw}}
async function fetchCrypto(sym,tf,total=5000){let all=[],end;while(all.length<total){let limit=Math.min(1000,total-all.length),u=`https://api.binance.com/api/v3/klines?symbol=${sym}&interval=${tf}&limit=${limit}`+(end?`&endTime=${end}`:'');let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('Binance '+r.status);let a=await r.json();if(!a.length)break;let c=a.map(x=>({t:+x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4],v:+x[5]}));all=[...c,...all];end=c[0].t-1;if(a.length<limit)break}let seen=new Set();return all.filter(x=>!seen.has(x.t)&&seen.add(x.t)).slice(-total)}
async function fetchB3(ticker,code){let token=localStorage.getItem('brapi_token')||'';if(!token)throw Error('Salve o token BRAPI antes de testar B3.');let cfg=B3CFG[code]||B3CFG.D1,url=`https://brapi.dev/api/v2/stocks/historical?symbols=${encodeURIComponent(ticker)}&range=${cfg.range}&interval=${cfg.interval}&sortOrder=asc`,r=await fetch(url,{headers:{Authorization:'Bearer '+token},cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.message||('BRAPI '+r.status));let item=j?.results?.[0]||{},payload=item?.data||item,arr=payload?.historicalDataPrice||[];return arr.map(x=>({t:+(x.date??x.datetime??x.timestamp??0),o:+(x.open??x.close),h:+(x.high??x.close),l:+(x.low??x.close),c:+x.close,v:+(x.volume??0)})).filter(x=>[x.o,x.h,x.l,x.c].every(Number.isFinite)).sort((a,b)=>a.t-b.t)}
function config(){return{fee:+($('#btFee')?.value||0.10)/100,slip:+($('#btSlip')?.value||0.03)/100,stopATR:+($('#btStopATR')?.value||1.5),targetR:+($('#btTargetR')?.value||1.5),horizon:+($('#btHorizon')?.value||30),nonOverlap:$('#btOverlap')?.value!=='allow'}}
function trade(c,i,s,cfg){if(i+1>=c.length)return null;let entryRaw=c[i+1].o,a=s.atr;if(!Number.isFinite(a)||a<=0)return null;let buy=s.dir==='BUY',entry=buy?entryRaw*(1+cfg.slip):entryRaw*(1-cfg.slip),risk=cfg.stopATR*a,stop=buy?entry-risk:entry+risk,target=buy?entry+risk*cfg.targetR:entry-risk*cfg.targetR,lastJ=i+1;
for(let j=i+1;j<Math.min(c.length,i+1+cfg.horizon);j++){lastJ=j;let q=c[j],hs=buy?q.l<=stop:q.h>=stop,ht=buy?q.h>=target:q.l<=target;if(hs&&ht){let gross=-1,cost=((cfg.fee+cfg.slip)*2*entry)/risk;return{r:gross-cost,result:'LOSS',exit:j,reason:'STOP_AMBIGUO'}}if(hs){let cost=((cfg.fee+cfg.slip)*2*entry)/risk;return{r:-1-cost,result:'LOSS',exit:j,reason:'STOP'}}if(ht){let cost=((cfg.fee+cfg.slip)*2*entry)/risk;return{r:cfg.targetR-cost,result:'WIN',exit:j,reason:'TARGET'}}}
let exit=c[lastJ].c,gross=(buy?(exit-entry):(entry-exit))/risk,cost=((cfg.fee+cfg.slip)*2*entry)/risk;return{r:gross-cost,result:gross>=0?'WIN':'LOSS',exit:lastJ,reason:'TIME'}}
function metrics(trades){let n=trades.length,w=trades.filter(x=>x.r>0),l=trades.filter(x=>x.r<=0),gp=w.reduce((s,x)=>s+x.r,0),gl=Math.abs(l.reduce((s,x)=>s+x.r,0)),eq=0,peak=0,dd=0,cw=0,cl=0,mw=0,ml=0;for(let x of trades){eq+=x.r;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq);if(x.r>0){cw++;cl=0;mw=Math.max(mw,cw)}else{cl++;cw=0;ml=Math.max(ml,cl)}}return{n,w:w.length,l:l.length,win:n?w.length/n*100:0,pf:gl?gp/gl:(gp?99:0),exp:n?eq/n:0,net:eq,dd,mw,ml}}
function runRange(c,start,end,min,cfg){let out=[],busyUntil=-1;for(let i=Math.max(120,start);i<Math.min(end,c.length-2);i++){if(cfg.nonOverlap&&i<=busyUntil)continue;let s=signal(c.slice(0,i+1));if(s.score<min)continue;let t=trade(c,i,s,cfg);if(!t)continue;out.push({...t,t:c[i].t,score:s.score,dir:s.dir,rsi:s.rsi,vr:s.vr});if(cfg.nonOverlap)busyUntil=t.exit}return out}
function row(name,m){return `<tr><td>${name}</td><td>${m.n}</td><td>${fmt(m.win,1)}%</td><td>${fmt(m.pf,2)}</td><td>${fmt(m.exp,3)}R</td><td>${fmt(m.net,2)}R</td><td>${fmt(m.dd,2)}R</td><td>${m.ml}</td></tr>`}
function saveRun(run){let a=[];try{a=JSON.parse(localStorage.getItem('ep_backtest_runs')||'[]')}catch{}a.push(run);if(a.length>100)a=a.slice(-100);localStorage.setItem('ep_backtest_runs',JSON.stringify(a));window.dispatchEvent(new CustomEvent('ep-statistics-updated'))}
function inject(){let area=$('#backtestArea');if(!area||$('#btRigorous'))return;let d=document.createElement('div');d.id='btRigorous';d.innerHTML=`<h3>Configuração do Backtest Rigoroso</h3><div class="bt-controls"><label>Fee por lado (%)<input id="btFee" type="number" step="0.01" value="0.10"></label><label>Slippage por lado (%)<input id="btSlip" type="number" step="0.01" value="0.03"></label><label>Stop ATR<input id="btStopATR" type="number" step="0.1" value="1.5"></label><label>Alvo (R)<input id="btTargetR" type="number" step="0.1" value="1.5"></label><label>Máx. candles<input id="btHorizon" type="number" step="1" value="30"></label><label>Overlap<select id="btOverlap"><option value="block" selected>Bloquear sobreposição</option><option value="allow">Permitir</option></select></label></div><p class="sub"><b>Regra conservadora:</b> sinal calculado no fechamento do candle; entrada somente na abertura do candle seguinte. Se stop e alvo forem tocados no mesmo candle, conta STOP. Custos são descontados. O teste técnico não reproduz notícias/OI/book históricos que não estejam disponíveis.</p>`;let controls=area.querySelector('.bt-controls');controls?.after(d)}
function fill(){let m=$('#btMarket')?.value||'crypto',a=$('#btAsset'),items=m==='b3'?B3:CRYPTO;if(a)a.innerHTML=items.map(([s,n])=>`<option value="${s}">${m==='b3'?s+' — '+n:n+'/USDT'}</option>`).join('')}
async function run(){let btn=$('#btRun'),st=$('#btStatus'),out=$('#btResults');if(!btn)return;btn.disabled=true;out.innerHTML='';try{let market=$('#btMarket').value,sym=$('#btAsset').value,code=$('#btTf').value,min=+$('#btMin').value,cfg=config();st.textContent='Baixando histórico e executando teste sem look-ahead...';let c=market==='b3'?await fetchB3(sym,code):await fetchCrypto(sym,TFS[code]||'15m',5000);if(c.length<500)throw Error(`Histórico insuficiente para teste rigoroso (${c.length} candles).`);let d1=Math.floor(c.length*.60),d2=Math.floor(c.length*.80),dev=runRange(c,0,d1,min,cfg),val=runRange(c,d1,d2,min,cfg),oos=runRange(c,d2,c.length,min,cfg),all=[...dev,...val,...oos],md=metrics(dev),mv=metrics(val),mo=metrics(oos),ma=metrics(all),approved=mo.n>=30&&mo.pf>1.2&&mo.exp>0&&mo.dd<=Math.max(8,mo.net*.6);out.innerHTML=`<div class="bt-kpis"><div><b>${ma.n}</b><span>operações</span></div><div><b>${fmt(ma.win,1)}%</b><span>acerto total</span></div><div><b>${fmt(ma.pf,2)}</b><span>PF total</span></div><div><b>${fmt(ma.exp,3)}R</b><span>expectativa</span></div><div><b>${fmt(ma.dd,2)}R</b><span>drawdown</span></div><div><b>${approved?'APROVADO':'NÃO APROVADO'}</b><span>teste OOS</span></div></div><h3>Separação temporal 60 / 20 / 20</h3><div class="bt-table-wrap"><table class="bt-table"><thead><tr><th>Bloco</th><th>Ops</th><th>Acerto</th><th>PF</th><th>Expect.</th><th>Resultado</th><th>DD</th><th>Máx perdas</th></tr></thead><tbody>${row('Desenvolvimento 60%',md)}${row('Validação 20%',mv)}${row('OUT-OF-SAMPLE 20%',mo)}${row('TOTAL',ma)}</tbody></table></div><p class="sub"><b>OOS:</b> ${mo.n} operações • PF ${fmt(mo.pf,2)} • expectativa ${fmt(mo.exp,3)}R. Critério inicial: ≥30 operações, PF &gt;1,20 e expectativa positiva. Esse critério ainda será calibrado pela Central Estatística, sem usar o OOS para escolher parâmetros.</p>`;
saveRun({ts:Date.now(),market,sym,tf:code,min,candles:c.length,cfg,dev:md,val:mv,oos:mo,total:ma,approved});st.textContent=`Backtest rigoroso concluído • ${sym} • ${code} • ${c.length} candles`; }catch(e){console.error(e);st.textContent='Falha no backtest rigoroso: '+e.message}finally{btn.disabled=false}}
function init(){inject();$('#btMarket')?.addEventListener('change',fill);let b=$('#btRun');if(b){let clone=b.cloneNode(true);b.parentNode.replaceChild(clone,b);clone.addEventListener('click',run)}fill()}
setTimeout(init,150)
})();