(()=>{
const $=s=>document.querySelector(s),REFRESH_MS=30*60*1000;
const PROXY_URL='https://iayxjarkeefbzjbpfulr.supabase.co/functions/v1/gnews-proxy';
const BLOCK_MAX_AGE_MIN=180,ATTENTION_MAX_AGE_MIN=360,DISPLAY_MAX_AGE_MIN=1440;
const CRYPTO={BTCUSDT:['Bitcoin','BTC'],ETHUSDT:['Ethereum','ETH'],SOLUSDT:['Solana','SOL'],BNBUSDT:['BNB'],XRPUSDT:['XRP','Ripple'],ADAUSDT:['Cardano','ADA'],DOGEUSDT:['Dogecoin','DOGE'],AVAXUSDT:['Avalanche','AVAX'],LINKUSDT:['Chainlink','LINK'],DOTUSDT:['Polkadot','DOT'],LTCUSDT:['Litecoin','LTC'],BCHUSDT:['Bitcoin Cash','BCH'],TRXUSDT:['Tron','TRX'],UNIUSDT:['Uniswap','UNI'],AAVEUSDT:['Aave','AAVE'],SUIUSDT:['Sui'],NEARUSDT:['Near Protocol','NEAR'],APTUSDT:['Aptos','APT'],ARBUSDT:['Arbitrum','ARB'],OPUSDT:['Optimism','OP']};
const B3={PETR4:['Petrobras','PETR4'],VALE3:['Vale','VALE3'],ITUB4:['Itaú','ITUB4'],BBAS3:['Banco do Brasil','BBAS3'],BBDC4:['Bradesco','BBDC4'],B3SA3:['B3SA3'],PRIO3:['PRIO','PRIO3'],WEGE3:['WEG','WEGE3'],EMBR3:['Embraer','EMBR3'],RENT3:['Localiza','RENT3'],SUZB3:['Suzano','SUZB3'],ELET3:['Eletrobras','ELET3'],EQTL3:['Equatorial','EQTL3'],RADL3:['RD Saúde','RADL3'],GGBR4:['Gerdau','GGBR4'],CSNA3:['CSN','CSNA3'],MGLU3:['Magazine Luiza','Magalu','MGLU3'],HAPV3:['Hapvida','HAPV3'],BHIA3:['Casas Bahia','BHIA3'],ABEV3:['Ambev','ABEV3']};
const NEG=['fraud','fraude','bankruptcy','falência','default','hack','exploit','investigation','investigação','lawsuit','processo','downgrade','sanction','sanções','ban','proibição','crash','profit warning','prejuízo','loss','fine','multa'];
const POS=['approval','approved','aprovação','lucro recorde','record profit','upgrade','partnership','parceria','acquisition','aquisição','buyback','recompra','dividend','dividendo','novo contrato','record revenue'];
const HIGH=['fomc','federal reserve','cpi','inflation','inflação','payroll','selic','copom','ipca','gdp','pib','war','guerra','sanction','sanções','sec','cvm','regulation','regulação','etf approval','bankruptcy','falência','fraud','fraude','hack','exploit'];
let state={status:'loading',error:'',articles:[],last:0,loading:false,delayed:false,risks:{crypto:{},b3:{}}};
function ensureUI(){if($('#newsImpactSection'))return;let a=[...document.querySelectorAll('section.card h2')].find(h=>h.textContent.includes('DETECTOR DE EXAUSTÃO'))?.parentElement,sec=document.createElement('section');sec.id='newsImpactSection';sec.className='card';sec.innerHTML=`<h2>NOTÍCIAS & RISCO DE REVERSÃO</h2><p class="sub">🟢 online • 🟡 atenção • 🔴 alto impacto/offline. Notícias antigas não bloqueiam entrada como se fossem novas.</p><div style="display:flex;gap:10px;align-items:center;margin-top:10px;flex-wrap:wrap"><button id="refreshNews" style="max-width:220px">Atualizar notícias agora</button><b id="newsHealth">🟡 CONECTANDO AO PROXY...</b><span id="newsStatus" class="sub"></span></div><div id="newsImpactPanel" class="decision-grid" style="margin-top:12px"></div><small class="sub">Conexão segura: EP → Supabase gnews-proxy → GNews. A chave GNews fica protegida nos Secrets do Supabase e não é enviada pelo navegador.</small>`;a?.parentNode?.insertBefore(sec,a.nextSibling);let st=document.createElement('style');st.textContent=`.news-card{background:#091827;border:1px solid #29415e;border-radius:12px;padding:12px}.news-card.high,.news-card.offline{border-color:#a84757;background:#25131a}.news-card.medium{border-color:#9b7c2a;background:#241f12}.news-card.normal{border-color:#2e8d6e;background:#0b211b}.news-headline{font-weight:700;margin:8px 0;line-height:1.35}.news-headline a{color:#d7e7f7}`;document.head.appendChild(st)}
function norm(s){return(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function has(t,a){t=norm(t);return a.some(x=>t.includes(norm(x)))}
function assets(){return{crypto:$('#chartCryptoPair')?.value||$('#pair')?.value||'BTCUSDT',b3:$('#chartB3Pair')?.value||$('#b3Pair')?.value||'PETR4'}}
function age(x){let t=Date.parse(x);return Number.isFinite(t)?Math.max(0,(Date.now()-t)/60000):9999}
function dedupe(list){let seen=new Set();return list.filter(a=>{let k=norm(a.title||a.url||'');if(!k||seen.has(k))return false;seen.add(k);return true})}
function score(a){let t=`${a.title||''} ${a.description||''}`,ag=age(a.publishedAt),rec=ag<=60?25:ag<=180?18:ag<=360?8:0,neg=has(t,NEG)?25:0,pos=has(t,POS)?20:0,imp=Math.min(100,20+rec+(has(t,HIGH)?40:0)+Math.max(neg,pos));return{impact:imp,direction:neg>pos?'negative':pos>neg?'positive':'uncertain',age:ag}}
function classify(asset,market){if(state.status!=='online')return{status:state.status,level:'offline',score:0,direction:'uncertain',headline:'Fonte de notícias indisponível',reversalRisk:'desconhecido'};let names=(market==='crypto'?CRYPTO:B3)[asset]||[asset],pool=[];for(let a of dedupe(state.articles)){let text=`${a.title||''} ${a.description||''}`,s=score(a),direct=names.some(n=>norm(text).includes(norm(n))),macro=has(text,HIGH);if((direct||macro)&&s.age<=DISPLAY_MAX_AGE_MIN)pool.push({...a,...s,direct,macro})}pool.sort((a,b)=>(b.direct-a.direct)||(a.age-b.age)||(b.impact-a.impact));let top=pool[0];if(!top)return{status:'online',level:'normal',score:0,direction:'uncertain',headline:'Sem notícia relevante recente',reversalRisk:'baixo'};let n=Math.min(100,top.impact+(top.direct?10:0)),level=n>=75?'high':n>=50?'medium':'normal';if(top.age>ATTENTION_MAX_AGE_MIN)level='normal';else if(top.age>BLOCK_MAX_AGE_MIN&&level==='high')level='medium';return{status:'online',level,score:n,direction:top.direction,headline:top.title||'Notícia relevante',url:top.url,source:top.source?.name||'',ageMin:top.age,direct:top.direct,reversalRisk:level==='high'?'alto':level==='medium'?'moderado':'baixo'}}
function rebuild(){let a=assets();state.risks.crypto[a.crypto]=classify(a.crypto,'crypto');state.risks.b3[a.b3]=classify(a.b3,'b3');render();window.dispatchEvent(new CustomEvent('news-impact-updated',{detail:{status:state.status}}))}
function health(){let e=$('#newsHealth');if(!e)return;if(state.status==='online'){e.textContent=state.delayed?'🟡 NOTÍCIAS ONLINE • ATRASO DO PLANO':'🟢 NOTÍCIAS ONLINE';e.style.color=state.delayed?'#ffd06c':'#4de0a0'}else if(state.status==='offline'){e.textContent='🔴 API DE NOTÍCIAS OFFLINE/ERRO';e.style.color='#ff7c86'}else{e.textContent='🟡 CONECTANDO AO PROXY...';e.style.color='#ffd06c'}}
async function callProxy(q){const u=new URL(PROXY_URL);u.searchParams.set('q',q);u.searchParams.set('max','10');const r=await fetch(u.toString(),{method:'GET',mode:'cors',cache:'no-store'});const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch{j={message:text||`HTTP ${r.status}`}}if(!r.ok||j.errors||j.error)throw Error(Array.isArray(j.errors)?j.errors[0]:(j.message||j.error||`HTTP ${r.status}`));return j}
async function fetchNews(){if(state.loading)return;state.loading=true;state.status='loading';state.delayed=false;health();$('#newsStatus').textContent='Buscando notícias via Supabase...';try{const a=assets(),cn=(CRYPTO[a.crypto]||[a.crypto])[0],bn=(B3[a.b3]||[a.b3])[0];let articles=[];for(const q of [cn,bn,'Federal Reserve inflação juros']){const j=await callProxy(q);if(Array.isArray(j.articles))articles.push(...j.articles);if(j?.information?.realTimeArticles?.message)state.delayed=true}state.articles=dedupe(articles).sort((x,y)=>age(x.publishedAt)-age(y.publishedAt));state.last=Date.now();state.status='online';state.error='';rebuild();$('#newsStatus').textContent=`${state.articles.length} artigos únicos via proxy • auto 30 min`}catch(e){state.status='offline';state.error=e?.message||'Falha de conexão';state.articles=[];rebuild();const hint=e instanceof TypeError?' • chamada externa bloqueada antes da resposta':'';$('#newsStatus').textContent='Falha no proxy/notícias: '+state.error+hint}finally{state.loading=false;health()}}
function pill(r){if(r.status!=='online')return'🔴 FONTE OFFLINE / RISCO DESCONHECIDO';let i=r.level==='high'?'🔴':r.level==='medium'?'🟡':'🟢';return`${i} ${r.level==='high'?'ALTO IMPACTO':r.level==='medium'?'ATENÇÃO':'INFORMATIVO'} • ${r.score}/100`}
function card(asset,market){let r=state.risks[market]?.[asset]||classify(asset,market),name=market==='crypto'?asset.replace('USDT','/USDT'):asset,action=r.status!=='online'?'BLOQUEAR CONFIRMAÇÃO AUTOMÁTICA':r.level==='high'?'BLOQUEAR NOVA ENTRADA':r.level==='medium'?'REDUZIR CONFIANÇA':'FILTRO LIBERADO';let freshness=r.ageMin==null?'':r.ageMin<=180?'RECENTE':r.ageMin<=360?'ENVELHECENDO':'ANTIGA — NÃO BLOQUEIA';return`<div class="news-card ${r.status!=='online'?'offline':r.level}"><div class=row><b>${name}</b><b>${pill(r)}</b></div><div class=news-headline>${r.url?`<a href="${r.url}" target="_blank" rel="noopener noreferrer">${r.headline}</a>`:r.headline}</div><div class=row><span>Risco de reversão</span><b>${String(r.reversalRisk).toUpperCase()}</b></div><div class=row><span>Ação no Motor Único</span><b>${action}</b></div>${r.ageMin!=null?`<small>${Math.round(r.ageMin)} min desde a publicação • ${freshness}${r.source?' • '+r.source:''}</small>`:''}</div>`}
function render(){let e=$('#newsImpactPanel');if(!e)return;let a=assets();e.innerHTML=card(a.crypto,'crypto')+card(a.b3,'b3');health()}
function getRisk(k,m){return state.risks?.[m]?.[k]||classify(k,m)}
function init(){ensureUI();window.EPNewsImpact={getRisk,refresh:fetchNews,getStatus:()=>state.status,getLastUpdate:()=>state.last,REFRESH_MS,PROXY_URL};$('#refreshNews')?.addEventListener('click',fetchNews);window.addEventListener('ep-auto-focus',()=>{rebuild();if(Date.now()-state.last>10*60*1000)fetchNews()});window.addEventListener('crypto-data-updated',render);window.addEventListener('b3-data-updated',render);fetchNews();setInterval(()=>{if(!document.hidden)fetchNews()},REFRESH_MS)}
setTimeout(init,700)
})();